### ISSUE TITLE
Cannot use api with Servobox (RR Servo Starter Kit) via Ethernet interface on Window10 OS.

### ISSUE THREAD

**Issue by ghost** [rozum-robotics/Rozum-Servo-Drives-API#4]
I have a problem using rozum servo drives API with Ethernet on Window10 OS. 
But I can use this API with Ethernet on Ubuntu without a problem.
I tried to run an example of python script by running this command, `python read_servo_max_velocity.py --interface 192.168.0.123 --servo_1_id 123` which the result is
```
$ python read_servo_max_velocity.py --interface 192.168.0.123 --servo_1_id 123
INFO:read_servo_max_velocity.py:Initializing ServoApi
INFO:read_servo_max_velocity.py:Initializing interface 192.168.0.123
ERROR:  usbcan_open_device: can't open serial device 192.168.0.123
INFO:read_servo_max_velocity.py:Initializing servo id 123
Traceback (most recent call last):
  File ".\read_servo_max_velocity.py", line 30, in <module>
    max_velocity = servo.get_max_velocity()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\rdrive\servo\api.py", line 254, in get_max_velocity
    ServoError.handle(status)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\rdrive\servo\api.py", line 68, in handle
    raise ServoError(code, RET_STATUS_MESSAGE[code])
rdrive.servo.api.ServoError: Bad interface or servo instance (null)
Exception ignored in: <function ServoApi.__del__ at 0x0000010DD29A02F0>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\rdrive\servo\api.py", line 1182, in __del__
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\rdrive\servo\api.py", line 1124, in deinit_interface
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\rdrive\servo\api.py", line 68, in handle
rdrive.servo.api.ServoError: Bad interface or servo instance (null)
```
But as I said I can run this command on the Ubuntu20.04 and It worked fine.
Can anyone guide me what is wrong? 
Anyway I can run this api with Serial Interface and it work fine perfectly both on Window OS and Ubuntu OS.

**Comment by kmxm** [comment]
This is due to a fault on the build server so you get old versions of the DLLs without ethernet support on Windows. For a fast workaround, you may compile them on your own. The easiest way is to install Cygwin and MinGW compiler in it. You may then build DLLs from the console using the command: 'make -e OS=win64' in the 'c' folder of the API. Folder 'build-win-64bit' will be created where you should find compiled DLLs.

**Comment by ghost** [comment]
> This is due to a fault on the build server so you get old versions of the DLLs without ethernet support on Windows. For a fast workaround, you may compile them on your own. The easiest way is to install Cygwin and MinGW compiler in it. You may then build DLLs from the console using the command: 'make -e OS=win64' in the 'c' folder of the API. Folder 'build-win-64bit' will be created where you should find compiled DLLs.

Thank you very much. It works.
I appreciate your help
